language: python
python:
- '2.7'
virtualenv:
  system_site_packages: true
install:
- pip install --no-deps -r requirements.txt --use-mirrors
script: nosetests
deploy:
  provider: pypi
  user: marketplacedevsinternal
  password:
    secure: Q2ClHKjioMKLlnMPsno9eNwzIhSxAOEKHBLolNFpAXxnJfhQm0YEXr9JHAYIXVSkMicmgy2loi5QXhfNCPVkBrP1C8qJ6NVfA0bl96DQ8OYqr6oCZBZMFvKknOOiqL1VvGnilDDvrMoPoPiOR8ifZG3HpcVPL0xwka4iQQ99xoo=
  on:
    tags: true
notifications:
  irc:
    channels:
    - irc.mozilla.org#marketplace
    on_success: change
    on_failure: always
